FROM node:19.5.0-alpine3.17 AS builder

WORKDIR /usr/src/app
#WORKDIR /usr/src

COPY package.json package-lock.json ./

RUN npm install

COPY . .

#                  --prod
RUN npm run build --prod

FROM nginx:1.19-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /usr/src/app/dist/ /usr/share/nginx/html/

COPY /src/assets /usr/share/nginx/html/assets

COPY nginx.conf /etc/nginx/nginx.conf



EXPOSE 80
